### YamlMime:ManagedReference
items:
- uid: FastEndpoints.Security
  commentId: N:FastEndpoints.Security
  id: FastEndpoints.Security
  children:
  - FastEndpoints.Security.AuthExtensions
  - FastEndpoints.Security.JWTBearer
  - FastEndpoints.Security.JWTBearer.TokenSigningStyle
  - FastEndpoints.Security.Permissions
  - FastEndpoints.Security.RefreshServiceOptions
  - FastEndpoints.Security.RefreshTokenService`2
  - FastEndpoints.Security.TokenRequest
  - FastEndpoints.Security.TokenResponse
  langs:
  - csharp
  - vb
  name: FastEndpoints.Security
  nameWithType: FastEndpoints.Security
  fullName: FastEndpoints.Security
  type: Namespace
  assemblies:
  - FastEndpoints.Security
references:
- uid: FastEndpoints.Security.AuthExtensions
  commentId: T:FastEndpoints.Security.AuthExtensions
  name: AuthExtensions
  nameWithType: AuthExtensions
  fullName: FastEndpoints.Security.AuthExtensions
- uid: FastEndpoints.Security.JWTBearer
  commentId: T:FastEndpoints.Security.JWTBearer
  name: JWTBearer
  nameWithType: JWTBearer
  fullName: FastEndpoints.Security.JWTBearer
- uid: FastEndpoints.Security.JWTBearer.TokenSigningStyle
  commentId: T:FastEndpoints.Security.JWTBearer.TokenSigningStyle
  parent: FastEndpoints.Security
  name: JWTBearer.TokenSigningStyle
  nameWithType: JWTBearer.TokenSigningStyle
  fullName: FastEndpoints.Security.JWTBearer.TokenSigningStyle
- uid: FastEndpoints.Security.Permissions
  commentId: T:FastEndpoints.Security.Permissions
  name: Permissions
  nameWithType: Permissions
  fullName: FastEndpoints.Security.Permissions
- uid: FastEndpoints.Security.RefreshServiceOptions
  commentId: T:FastEndpoints.Security.RefreshServiceOptions
  name: RefreshServiceOptions
  nameWithType: RefreshServiceOptions
  fullName: FastEndpoints.Security.RefreshServiceOptions
- uid: FastEndpoints.Security.RefreshTokenService`2
  commentId: T:FastEndpoints.Security.RefreshTokenService`2
  name: RefreshTokenService<TRequest, TResponse>
  nameWithType: RefreshTokenService<TRequest, TResponse>
  fullName: FastEndpoints.Security.RefreshTokenService<TRequest, TResponse>
  nameWithType.vb: RefreshTokenService(Of TRequest, TResponse)
  fullName.vb: FastEndpoints.Security.RefreshTokenService(Of TRequest, TResponse)
  name.vb: RefreshTokenService(Of TRequest, TResponse)
  spec.csharp:
  - uid: FastEndpoints.Security.RefreshTokenService`2
    name: RefreshTokenService
    nameWithType: RefreshTokenService
    fullName: FastEndpoints.Security.RefreshTokenService
  - name: <
    nameWithType: <
    fullName: <
  - name: TRequest
    nameWithType: TRequest
    fullName: TRequest
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TResponse
    nameWithType: TResponse
    fullName: TResponse
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: FastEndpoints.Security.RefreshTokenService`2
    name: RefreshTokenService
    nameWithType: RefreshTokenService
    fullName: FastEndpoints.Security.RefreshTokenService
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TRequest
    nameWithType: TRequest
    fullName: TRequest
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TResponse
    nameWithType: TResponse
    fullName: TResponse
  - name: )
    nameWithType: )
    fullName: )
- uid: FastEndpoints.Security.TokenRequest
  commentId: T:FastEndpoints.Security.TokenRequest
  parent: FastEndpoints.Security
  name: TokenRequest
  nameWithType: TokenRequest
  fullName: FastEndpoints.Security.TokenRequest
- uid: FastEndpoints.Security.TokenResponse
  commentId: T:FastEndpoints.Security.TokenResponse
  name: TokenResponse
  nameWithType: TokenResponse
  fullName: FastEndpoints.Security.TokenResponse
- uid: FastEndpoints.Security
  commentId: N:FastEndpoints.Security
  name: FastEndpoints.Security
  nameWithType: FastEndpoints.Security
  fullName: FastEndpoints.Security
