### YamlMime:ManagedReference
items:
- uid: FastEndpoints.Security
  commentId: N:FastEndpoints.Security
  id: FastEndpoints.Security
  children:
  - FastEndpoints.Security.AuthExtensions
  - FastEndpoints.Security.CookieAuth
  - FastEndpoints.Security.JWTBearer
  - FastEndpoints.Security.JWTBearer.TokenSigningStyle
  - FastEndpoints.Security.Permissions
  - FastEndpoints.Security.RefreshServiceOptions
  - FastEndpoints.Security.RefreshTokenService`2
  - FastEndpoints.Security.TokenRequest
  - FastEndpoints.Security.TokenResponse
  langs:
  - csharp
  - vb
  name: FastEndpoints.Security
  nameWithType: FastEndpoints.Security
  fullName: FastEndpoints.Security
  type: Namespace
  assemblies:
  - FastEndpoints.Security
references:
- uid: FastEndpoints.Security.AuthExtensions
  commentId: T:FastEndpoints.Security.AuthExtensions
  href: FastEndpoints.Security.AuthExtensions.html
  name: AuthExtensions
  nameWithType: AuthExtensions
  fullName: FastEndpoints.Security.AuthExtensions
- uid: FastEndpoints.Security.CookieAuth
  commentId: T:FastEndpoints.Security.CookieAuth
  href: FastEndpoints.Security.CookieAuth.html
  name: CookieAuth
  nameWithType: CookieAuth
  fullName: FastEndpoints.Security.CookieAuth
- uid: FastEndpoints.Security.JWTBearer
  commentId: T:FastEndpoints.Security.JWTBearer
  href: FastEndpoints.Security.JWTBearer.html
  name: JWTBearer
  nameWithType: JWTBearer
  fullName: FastEndpoints.Security.JWTBearer
- uid: FastEndpoints.Security.JWTBearer.TokenSigningStyle
  commentId: T:FastEndpoints.Security.JWTBearer.TokenSigningStyle
  parent: FastEndpoints.Security
  href: FastEndpoints.Security.JWTBearer.html
  name: JWTBearer.TokenSigningStyle
  nameWithType: JWTBearer.TokenSigningStyle
  fullName: FastEndpoints.Security.JWTBearer.TokenSigningStyle
  spec.csharp:
  - uid: FastEndpoints.Security.JWTBearer
    name: JWTBearer
    href: FastEndpoints.Security.JWTBearer.html
  - name: .
  - uid: FastEndpoints.Security.JWTBearer.TokenSigningStyle
    name: TokenSigningStyle
    href: FastEndpoints.Security.JWTBearer.TokenSigningStyle.html
  spec.vb:
  - uid: FastEndpoints.Security.JWTBearer
    name: JWTBearer
    href: FastEndpoints.Security.JWTBearer.html
  - name: .
  - uid: FastEndpoints.Security.JWTBearer.TokenSigningStyle
    name: TokenSigningStyle
    href: FastEndpoints.Security.JWTBearer.TokenSigningStyle.html
- uid: FastEndpoints.Security.Permissions
  commentId: T:FastEndpoints.Security.Permissions
  href: FastEndpoints.Security.Permissions.html
  name: Permissions
  nameWithType: Permissions
  fullName: FastEndpoints.Security.Permissions
- uid: FastEndpoints.Security.RefreshServiceOptions
  commentId: T:FastEndpoints.Security.RefreshServiceOptions
  href: FastEndpoints.Security.RefreshServiceOptions.html
  name: RefreshServiceOptions
  nameWithType: RefreshServiceOptions
  fullName: FastEndpoints.Security.RefreshServiceOptions
- uid: FastEndpoints.Security.RefreshTokenService`2
  commentId: T:FastEndpoints.Security.RefreshTokenService`2
  href: FastEndpoints.Security.RefreshTokenService-2.html
  name: RefreshTokenService<TRequest, TResponse>
  nameWithType: RefreshTokenService<TRequest, TResponse>
  fullName: FastEndpoints.Security.RefreshTokenService<TRequest, TResponse>
  nameWithType.vb: RefreshTokenService(Of TRequest, TResponse)
  fullName.vb: FastEndpoints.Security.RefreshTokenService(Of TRequest, TResponse)
  name.vb: RefreshTokenService(Of TRequest, TResponse)
  spec.csharp:
  - uid: FastEndpoints.Security.RefreshTokenService`2
    name: RefreshTokenService
    href: FastEndpoints.Security.RefreshTokenService-2.html
  - name: <
  - name: TRequest
  - name: ','
  - name: " "
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: FastEndpoints.Security.RefreshTokenService`2
    name: RefreshTokenService
    href: FastEndpoints.Security.RefreshTokenService-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TRequest
  - name: ','
  - name: " "
  - name: TResponse
  - name: )
- uid: FastEndpoints.Security.TokenRequest
  commentId: T:FastEndpoints.Security.TokenRequest
  parent: FastEndpoints.Security
  href: FastEndpoints.Security.TokenRequest.html
  name: TokenRequest
  nameWithType: TokenRequest
  fullName: FastEndpoints.Security.TokenRequest
- uid: FastEndpoints.Security.TokenResponse
  commentId: T:FastEndpoints.Security.TokenResponse
  href: FastEndpoints.Security.TokenResponse.html
  name: TokenResponse
  nameWithType: TokenResponse
  fullName: FastEndpoints.Security.TokenResponse
- uid: FastEndpoints.Security
  commentId: N:FastEndpoints.Security
  href: FastEndpoints.html
  name: FastEndpoints.Security
  nameWithType: FastEndpoints.Security
  fullName: FastEndpoints.Security
  spec.csharp:
  - uid: FastEndpoints
    name: FastEndpoints
    href: FastEndpoints.html
  - name: .
  - uid: FastEndpoints.Security
    name: Security
    href: FastEndpoints.Security.html
  spec.vb:
  - uid: FastEndpoints
    name: FastEndpoints
    href: FastEndpoints.html
  - name: .
  - uid: FastEndpoints.Security
    name: Security
    href: FastEndpoints.Security.html
