### YamlMime:ManagedReference
items:
- uid: FastEndpoints.Swagger.AutoTagOverride
  commentId: T:FastEndpoints.Swagger.AutoTagOverride
  id: AutoTagOverride
  parent: FastEndpoints.Swagger
  children:
  - FastEndpoints.Swagger.AutoTagOverride.#ctor(System.String)
  - FastEndpoints.Swagger.AutoTagOverride.TagName
  langs:
  - csharp
  - vb
  name: AutoTagOverride
  nameWithType: AutoTagOverride
  fullName: FastEndpoints.Swagger.AutoTagOverride
  type: Class
  assemblies:
  - FastEndpoints.Swagger
  namespace: FastEndpoints.Swagger
  summary: represents an auto-tag override value.
  example: []
  syntax:
    content: public sealed class AutoTagOverride
    content.vb: Public NotInheritable Class AutoTagOverride
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: FastEndpoints.Swagger.AutoTagOverride.#ctor(System.String)
  commentId: M:FastEndpoints.Swagger.AutoTagOverride.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: FastEndpoints.Swagger.AutoTagOverride
  langs:
  - csharp
  - vb
  name: AutoTagOverride(string)
  nameWithType: AutoTagOverride.AutoTagOverride(string)
  fullName: FastEndpoints.Swagger.AutoTagOverride.AutoTagOverride(string)
  type: Constructor
  assemblies:
  - FastEndpoints.Swagger
  namespace: FastEndpoints.Swagger
  summary: represents an auto-tag override value.
  example: []
  syntax:
    content: public AutoTagOverride(string tagName)
    parameters:
    - id: tagName
      type: System.String
      description: ''
    content.vb: Public Sub New(tagName As String)
  overload: FastEndpoints.Swagger.AutoTagOverride.#ctor*
  nameWithType.vb: AutoTagOverride.New(String)
  fullName.vb: FastEndpoints.Swagger.AutoTagOverride.New(String)
  name.vb: New(String)
- uid: FastEndpoints.Swagger.AutoTagOverride.TagName
  commentId: P:FastEndpoints.Swagger.AutoTagOverride.TagName
  id: TagName
  parent: FastEndpoints.Swagger.AutoTagOverride
  langs:
  - csharp
  - vb
  name: TagName
  nameWithType: AutoTagOverride.TagName
  fullName: FastEndpoints.Swagger.AutoTagOverride.TagName
  type: Property
  assemblies:
  - FastEndpoints.Swagger
  namespace: FastEndpoints.Swagger
  syntax:
    content: public string TagName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property TagName As String
  overload: FastEndpoints.Swagger.AutoTagOverride.TagName*
references:
- uid: FastEndpoints.Swagger
  commentId: N:FastEndpoints.Swagger
  href: FastEndpoints.html
  name: FastEndpoints.Swagger
  nameWithType: FastEndpoints.Swagger
  fullName: FastEndpoints.Swagger
  spec.csharp:
  - uid: FastEndpoints
    name: FastEndpoints
    href: FastEndpoints.html
  - name: .
  - uid: FastEndpoints.Swagger
    name: Swagger
    href: FastEndpoints.Swagger.html
  spec.vb:
  - uid: FastEndpoints
    name: FastEndpoints
    href: FastEndpoints.html
  - name: .
  - uid: FastEndpoints.Swagger
    name: Swagger
    href: FastEndpoints.Swagger.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: FastEndpoints.Swagger.AutoTagOverride.#ctor*
  commentId: Overload:FastEndpoints.Swagger.AutoTagOverride.#ctor
  href: FastEndpoints.Swagger.AutoTagOverride.html#FastEndpoints_Swagger_AutoTagOverride__ctor_System_String_
  name: AutoTagOverride
  nameWithType: AutoTagOverride.AutoTagOverride
  fullName: FastEndpoints.Swagger.AutoTagOverride.AutoTagOverride
  nameWithType.vb: AutoTagOverride.New
  fullName.vb: FastEndpoints.Swagger.AutoTagOverride.New
  name.vb: New
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: FastEndpoints.Swagger.AutoTagOverride.TagName*
  commentId: Overload:FastEndpoints.Swagger.AutoTagOverride.TagName
  href: FastEndpoints.Swagger.AutoTagOverride.html#FastEndpoints_Swagger_AutoTagOverride_TagName
  name: TagName
  nameWithType: AutoTagOverride.TagName
  fullName: FastEndpoints.Swagger.AutoTagOverride.TagName
