### YamlMime:ManagedReference
items:
- uid: FastEndpoints.Swagger
  commentId: N:FastEndpoints.Swagger
  id: FastEndpoints.Swagger
  children:
  - FastEndpoints.Swagger.DocumentOptions
  - FastEndpoints.Swagger.Extensions
  - FastEndpoints.Swagger.GlobalConfig
  - FastEndpoints.Swagger.TagCase
  langs:
  - csharp
  - vb
  name: FastEndpoints.Swagger
  nameWithType: FastEndpoints.Swagger
  fullName: FastEndpoints.Swagger
  type: Namespace
  assemblies:
  - FastEndpoints.Swagger
references:
- uid: FastEndpoints.Swagger.DocumentOptions
  commentId: T:FastEndpoints.Swagger.DocumentOptions
  href: FastEndpoints.Swagger.DocumentOptions.html
  name: DocumentOptions
  nameWithType: DocumentOptions
  fullName: FastEndpoints.Swagger.DocumentOptions
- uid: FastEndpoints.Swagger.Extensions
  commentId: T:FastEndpoints.Swagger.Extensions
  href: FastEndpoints.Swagger.Extensions.html
  name: Extensions
  nameWithType: Extensions
  fullName: FastEndpoints.Swagger.Extensions
- uid: FastEndpoints.Swagger.GlobalConfig
  commentId: T:FastEndpoints.Swagger.GlobalConfig
  href: FastEndpoints.Swagger.GlobalConfig.html
  name: GlobalConfig
  nameWithType: GlobalConfig
  fullName: FastEndpoints.Swagger.GlobalConfig
- uid: FastEndpoints.Swagger.TagCase
  commentId: T:FastEndpoints.Swagger.TagCase
  parent: FastEndpoints.Swagger
  href: FastEndpoints.Swagger.TagCase.html
  name: TagCase
  nameWithType: TagCase
  fullName: FastEndpoints.Swagger.TagCase
- uid: FastEndpoints.Swagger
  commentId: N:FastEndpoints.Swagger
  href: FastEndpoints.html
  name: FastEndpoints.Swagger
  nameWithType: FastEndpoints.Swagger
  fullName: FastEndpoints.Swagger
  spec.csharp:
  - uid: FastEndpoints
    name: FastEndpoints
    href: FastEndpoints.html
  - name: .
  - uid: FastEndpoints.Swagger
    name: Swagger
    href: FastEndpoints.Swagger.html
  spec.vb:
  - uid: FastEndpoints
    name: FastEndpoints
    href: FastEndpoints.html
  - name: .
  - uid: FastEndpoints.Swagger
    name: Swagger
    href: FastEndpoints.Swagger.html
