### YamlMime:ManagedReference
items:
- uid: FastEndpoints.Swagger.ValidationSchemaProcessor
  commentId: T:FastEndpoints.Swagger.ValidationSchemaProcessor
  id: ValidationSchemaProcessor
  parent: FastEndpoints.Swagger
  children:
  - FastEndpoints.Swagger.ValidationSchemaProcessor.#ctor
  - FastEndpoints.Swagger.ValidationSchemaProcessor.Process(SchemaProcessorContext)
  langs:
  - csharp
  - vb
  name: ValidationSchemaProcessor
  nameWithType: ValidationSchemaProcessor
  fullName: FastEndpoints.Swagger.ValidationSchemaProcessor
  type: Class
  source:
    id: ValidationSchemaProcessor
    path: D:\SOURCE-CONTROL\FastEndpoints\Api-Reference\Source\src\Swagger\ValidationSchemaProcessor.cs
    startLine: 35
  assemblies:
  - FastEndpoints.Swagger
  namespace: FastEndpoints.Swagger
  syntax:
    content: 'public class ValidationSchemaProcessor : ISchemaProcessor'
    content.vb: >-
      Public Class ValidationSchemaProcessor

          Inherits ISchemaProcessor
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: FastEndpoints.Swagger.ValidationSchemaProcessor.#ctor
  commentId: M:FastEndpoints.Swagger.ValidationSchemaProcessor.#ctor
  id: '#ctor'
  parent: FastEndpoints.Swagger.ValidationSchemaProcessor
  langs:
  - csharp
  - vb
  name: ValidationSchemaProcessor()
  nameWithType: ValidationSchemaProcessor.ValidationSchemaProcessor()
  fullName: FastEndpoints.Swagger.ValidationSchemaProcessor.ValidationSchemaProcessor()
  type: Constructor
  source:
    id: .ctor
    path: D:\SOURCE-CONTROL\FastEndpoints\Api-Reference\Source\src\Swagger\ValidationSchemaProcessor.cs
    startLine: 42
  assemblies:
  - FastEndpoints.Swagger
  namespace: FastEndpoints.Swagger
  syntax:
    content: public ValidationSchemaProcessor()
    content.vb: Public Sub New
  overload: FastEndpoints.Swagger.ValidationSchemaProcessor.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: FastEndpoints.Swagger.ValidationSchemaProcessor.Process(SchemaProcessorContext)
  commentId: M:FastEndpoints.Swagger.ValidationSchemaProcessor.Process(SchemaProcessorContext)
  id: Process(SchemaProcessorContext)
  parent: FastEndpoints.Swagger.ValidationSchemaProcessor
  langs:
  - csharp
  - vb
  name: Process(SchemaProcessorContext)
  nameWithType: ValidationSchemaProcessor.Process(SchemaProcessorContext)
  fullName: FastEndpoints.Swagger.ValidationSchemaProcessor.Process(SchemaProcessorContext)
  type: Method
  source:
    id: Process
    path: D:\SOURCE-CONTROL\FastEndpoints\Api-Reference\Source\src\Swagger\ValidationSchemaProcessor.cs
    startLine: 48
  assemblies:
  - FastEndpoints.Swagger
  namespace: FastEndpoints.Swagger
  syntax:
    content: public void Process(SchemaProcessorContext context)
    parameters:
    - id: context
      type: SchemaProcessorContext
    content.vb: Public Sub Process(context As SchemaProcessorContext)
  overload: FastEndpoints.Swagger.ValidationSchemaProcessor.Process*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: FastEndpoints.Swagger
  commentId: N:FastEndpoints.Swagger
  name: FastEndpoints.Swagger
  nameWithType: FastEndpoints.Swagger
  fullName: FastEndpoints.Swagger
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: FastEndpoints.Swagger.ValidationSchemaProcessor.#ctor*
  commentId: Overload:FastEndpoints.Swagger.ValidationSchemaProcessor.#ctor
  name: ValidationSchemaProcessor
  nameWithType: ValidationSchemaProcessor.ValidationSchemaProcessor
  fullName: FastEndpoints.Swagger.ValidationSchemaProcessor.ValidationSchemaProcessor
- uid: FastEndpoints.Swagger.ValidationSchemaProcessor.Process*
  commentId: Overload:FastEndpoints.Swagger.ValidationSchemaProcessor.Process
  name: Process
  nameWithType: ValidationSchemaProcessor.Process
  fullName: FastEndpoints.Swagger.ValidationSchemaProcessor.Process
- uid: SchemaProcessorContext
  commentId: '!:SchemaProcessorContext'
  isExternal: true
  name: SchemaProcessorContext
  nameWithType: SchemaProcessorContext
  fullName: SchemaProcessorContext
