### YamlMime:ManagedReference
items:
- uid: FastEndpoints.Security
  commentId: N:FastEndpoints.Security
  id: FastEndpoints.Security
  children:
  - FastEndpoints.Security.AuthExtensions
  - FastEndpoints.Security.CookieAuth
  - FastEndpoints.Security.JwtBearer
  - FastEndpoints.Security.JwtCreationOptions
  - FastEndpoints.Security.JwtRevocationExtensions
  - FastEndpoints.Security.JwtRevocationMiddleware
  - FastEndpoints.Security.JwtSigningOptions
  - FastEndpoints.Security.Permissions
  - FastEndpoints.Security.RefreshServiceOptions
  - FastEndpoints.Security.RefreshTokenService`2
  - FastEndpoints.Security.TokenRequest
  - FastEndpoints.Security.TokenResponse
  - FastEndpoints.Security.TokenSigningStyle
  langs:
  - csharp
  - vb
  name: FastEndpoints.Security
  nameWithType: FastEndpoints.Security
  fullName: FastEndpoints.Security
  type: Namespace
  assemblies:
  - FastEndpoints.Security
references:
- uid: FastEndpoints.Security.AuthExtensions
  commentId: T:FastEndpoints.Security.AuthExtensions
  href: FastEndpoints.Security.AuthExtensions.html
  name: AuthExtensions
  nameWithType: AuthExtensions
  fullName: FastEndpoints.Security.AuthExtensions
- uid: FastEndpoints.Security.CookieAuth
  commentId: T:FastEndpoints.Security.CookieAuth
  href: FastEndpoints.Security.CookieAuth.html
  name: CookieAuth
  nameWithType: CookieAuth
  fullName: FastEndpoints.Security.CookieAuth
- uid: FastEndpoints.Security.JwtBearer
  commentId: T:FastEndpoints.Security.JwtBearer
  href: FastEndpoints.Security.JwtBearer.html
  name: JwtBearer
  nameWithType: JwtBearer
  fullName: FastEndpoints.Security.JwtBearer
- uid: FastEndpoints.Security.JwtCreationOptions
  commentId: T:FastEndpoints.Security.JwtCreationOptions
  parent: FastEndpoints.Security
  href: FastEndpoints.Security.JwtCreationOptions.html
  name: JwtCreationOptions
  nameWithType: JwtCreationOptions
  fullName: FastEndpoints.Security.JwtCreationOptions
- uid: FastEndpoints.Security.JwtSigningOptions
  commentId: T:FastEndpoints.Security.JwtSigningOptions
  href: FastEndpoints.Security.JwtSigningOptions.html
  name: JwtSigningOptions
  nameWithType: JwtSigningOptions
  fullName: FastEndpoints.Security.JwtSigningOptions
- uid: FastEndpoints.Security.Permissions
  commentId: T:FastEndpoints.Security.Permissions
  href: FastEndpoints.Security.Permissions.html
  name: Permissions
  nameWithType: Permissions
  fullName: FastEndpoints.Security.Permissions
- uid: FastEndpoints.Security.RefreshServiceOptions
  commentId: T:FastEndpoints.Security.RefreshServiceOptions
  href: FastEndpoints.Security.RefreshServiceOptions.html
  name: RefreshServiceOptions
  nameWithType: RefreshServiceOptions
  fullName: FastEndpoints.Security.RefreshServiceOptions
- uid: FastEndpoints.Security.RefreshTokenService`2
  commentId: T:FastEndpoints.Security.RefreshTokenService`2
  href: FastEndpoints.Security.RefreshTokenService-2.html
  name: RefreshTokenService<TRequest, TResponse>
  nameWithType: RefreshTokenService<TRequest, TResponse>
  fullName: FastEndpoints.Security.RefreshTokenService<TRequest, TResponse>
  nameWithType.vb: RefreshTokenService(Of TRequest, TResponse)
  fullName.vb: FastEndpoints.Security.RefreshTokenService(Of TRequest, TResponse)
  name.vb: RefreshTokenService(Of TRequest, TResponse)
  spec.csharp:
  - uid: FastEndpoints.Security.RefreshTokenService`2
    name: RefreshTokenService
    href: FastEndpoints.Security.RefreshTokenService-2.html
  - name: <
  - name: TRequest
  - name: ','
  - name: " "
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: FastEndpoints.Security.RefreshTokenService`2
    name: RefreshTokenService
    href: FastEndpoints.Security.RefreshTokenService-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TRequest
  - name: ','
  - name: " "
  - name: TResponse
  - name: )
- uid: FastEndpoints.Security.TokenRequest
  commentId: T:FastEndpoints.Security.TokenRequest
  parent: FastEndpoints.Security
  href: FastEndpoints.Security.TokenRequest.html
  name: TokenRequest
  nameWithType: TokenRequest
  fullName: FastEndpoints.Security.TokenRequest
- uid: FastEndpoints.Security.TokenResponse
  commentId: T:FastEndpoints.Security.TokenResponse
  href: FastEndpoints.Security.TokenResponse.html
  name: TokenResponse
  nameWithType: TokenResponse
  fullName: FastEndpoints.Security.TokenResponse
- uid: FastEndpoints.Security.JwtRevocationExtensions
  commentId: T:FastEndpoints.Security.JwtRevocationExtensions
  href: FastEndpoints.Security.JwtRevocationExtensions.html
  name: JwtRevocationExtensions
  nameWithType: JwtRevocationExtensions
  fullName: FastEndpoints.Security.JwtRevocationExtensions
- uid: FastEndpoints.Security.JwtRevocationMiddleware
  commentId: T:FastEndpoints.Security.JwtRevocationMiddleware
  href: FastEndpoints.Security.JwtRevocationMiddleware.html
  name: JwtRevocationMiddleware
  nameWithType: JwtRevocationMiddleware
  fullName: FastEndpoints.Security.JwtRevocationMiddleware
- uid: FastEndpoints.Security.TokenSigningStyle
  commentId: T:FastEndpoints.Security.TokenSigningStyle
  parent: FastEndpoints.Security
  href: FastEndpoints.Security.TokenSigningStyle.html
  name: TokenSigningStyle
  nameWithType: TokenSigningStyle
  fullName: FastEndpoints.Security.TokenSigningStyle
- uid: FastEndpoints.Security
  commentId: N:FastEndpoints.Security
  href: FastEndpoints.html
  name: FastEndpoints.Security
  nameWithType: FastEndpoints.Security
  fullName: FastEndpoints.Security
  spec.csharp:
  - uid: FastEndpoints
    name: FastEndpoints
    href: FastEndpoints.html
  - name: .
  - uid: FastEndpoints.Security
    name: Security
    href: FastEndpoints.Security.html
  spec.vb:
  - uid: FastEndpoints
    name: FastEndpoints
    href: FastEndpoints.html
  - name: .
  - uid: FastEndpoints.Security
    name: Security
    href: FastEndpoints.Security.html
