### YamlMime:ManagedReference
items:
- uid: FastEndpoints.Swagger.GlobalConfig
  commentId: T:FastEndpoints.Swagger.GlobalConfig
  id: GlobalConfig
  parent: FastEndpoints.Swagger
  children:
  - FastEndpoints.Swagger.GlobalConfig.EndpointRoutePrefix
  - FastEndpoints.Swagger.GlobalConfig.VersioningPrefix
  langs:
  - csharp
  - vb
  name: GlobalConfig
  nameWithType: GlobalConfig
  fullName: FastEndpoints.Swagger.GlobalConfig
  type: Class
  source:
    id: GlobalConfig
    path: D:\SOURCE-CONTROL\FastEndpoints\Library\Src\Swagger\GlobalConfig.cs
    startLine: 5
  assemblies:
  - FastEndpoints.Swagger
  namespace: FastEndpoints.Swagger
  summary: "\ngives access to the fastendpoints global configuration settings\n"
  example: []
  syntax:
    content: public static class GlobalConfig
    content.vb: Public Module GlobalConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: FastEndpoints.Swagger.GlobalConfig.VersioningPrefix
  commentId: P:FastEndpoints.Swagger.GlobalConfig.VersioningPrefix
  id: VersioningPrefix
  parent: FastEndpoints.Swagger.GlobalConfig
  langs:
  - csharp
  - vb
  name: VersioningPrefix
  nameWithType: GlobalConfig.VersioningPrefix
  fullName: FastEndpoints.Swagger.GlobalConfig.VersioningPrefix
  type: Property
  source:
    id: VersioningPrefix
    path: D:\SOURCE-CONTROL\FastEndpoints\Library\Src\Swagger\GlobalConfig.cs
    startLine: 10
  assemblies:
  - FastEndpoints.Swagger
  namespace: FastEndpoints.Swagger
  summary: "\nthe prefix used in front of the version (for example &apos;v&apos; produces &apos;v{version}&apos;).\n"
  example: []
  syntax:
    content: public static string VersioningPrefix { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared ReadOnly Property VersioningPrefix As String
  overload: FastEndpoints.Swagger.GlobalConfig.VersioningPrefix*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: FastEndpoints.Swagger.GlobalConfig.EndpointRoutePrefix
  commentId: P:FastEndpoints.Swagger.GlobalConfig.EndpointRoutePrefix
  id: EndpointRoutePrefix
  parent: FastEndpoints.Swagger.GlobalConfig
  langs:
  - csharp
  - vb
  name: EndpointRoutePrefix
  nameWithType: GlobalConfig.EndpointRoutePrefix
  fullName: FastEndpoints.Swagger.GlobalConfig.EndpointRoutePrefix
  type: Property
  source:
    id: EndpointRoutePrefix
    path: D:\SOURCE-CONTROL\FastEndpoints\Library\Src\Swagger\GlobalConfig.cs
    startLine: 15
  assemblies:
  - FastEndpoints.Swagger
  namespace: FastEndpoints.Swagger
  summary: "\nprefix for all routes (example &apos;api&apos;).\n"
  example: []
  syntax:
    content: public static string EndpointRoutePrefix { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared ReadOnly Property EndpointRoutePrefix As String
  overload: FastEndpoints.Swagger.GlobalConfig.EndpointRoutePrefix*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
references:
- uid: FastEndpoints.Swagger
  commentId: N:FastEndpoints.Swagger
  name: FastEndpoints.Swagger
  nameWithType: FastEndpoints.Swagger
  fullName: FastEndpoints.Swagger
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: FastEndpoints.Swagger.GlobalConfig.VersioningPrefix*
  commentId: Overload:FastEndpoints.Swagger.GlobalConfig.VersioningPrefix
  name: VersioningPrefix
  nameWithType: GlobalConfig.VersioningPrefix
  fullName: FastEndpoints.Swagger.GlobalConfig.VersioningPrefix
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: FastEndpoints.Swagger.GlobalConfig.EndpointRoutePrefix*
  commentId: Overload:FastEndpoints.Swagger.GlobalConfig.EndpointRoutePrefix
  name: EndpointRoutePrefix
  nameWithType: GlobalConfig.EndpointRoutePrefix
  fullName: FastEndpoints.Swagger.GlobalConfig.EndpointRoutePrefix
