### YamlMime:ManagedReference
items:
- uid: FastEndpoints.Config
  commentId: T:FastEndpoints.Config
  id: Config
  parent: FastEndpoints
  children:
  - FastEndpoints.Config.Binding
  - FastEndpoints.Config.Endpoints
  - FastEndpoints.Config.Errors
  - FastEndpoints.Config.Security
  - FastEndpoints.Config.Serializer
  - FastEndpoints.Config.Throttle
  - FastEndpoints.Config.Validation
  - FastEndpoints.Config.Versioning
  langs:
  - csharp
  - vb
  name: Config
  nameWithType: Config
  fullName: FastEndpoints.Config
  type: Class
  source:
    id: Config
    path: D:\SOURCE-CONTROL\FastEndpoints\Src\Library\Config\Config.cs
    startLine: 10
  assemblies:
  - FastEndpoints
  namespace: FastEndpoints
  summary: global configuration settings for FastEndpoints
  example: []
  syntax:
    content: public sealed class Config
    content.vb: Public NotInheritable Class Config
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: FastEndpoints.Config.Binding
  commentId: P:FastEndpoints.Config.Binding
  id: Binding
  parent: FastEndpoints.Config
  langs:
  - csharp
  - vb
  name: Binding
  nameWithType: Config.Binding
  fullName: FastEndpoints.Config.Binding
  type: Property
  source:
    id: Binding
    path: D:\SOURCE-CONTROL\FastEndpoints\Src\Library\Config\Config.cs
    startLine: 33
  assemblies:
  - FastEndpoints
  namespace: FastEndpoints
  summary: request binding settings
  example: []
  syntax:
    content: public BindingOptions Binding { get; }
    parameters: []
    return:
      type: FastEndpoints.BindingOptions
    content.vb: Public ReadOnly Property Binding As BindingOptions
  overload: FastEndpoints.Config.Binding*
- uid: FastEndpoints.Config.Endpoints
  commentId: P:FastEndpoints.Config.Endpoints
  id: Endpoints
  parent: FastEndpoints.Config
  langs:
  - csharp
  - vb
  name: Endpoints
  nameWithType: Config.Endpoints
  fullName: FastEndpoints.Config.Endpoints
  type: Property
  source:
    id: Endpoints
    path: D:\SOURCE-CONTROL\FastEndpoints\Src\Library\Config\Config.cs
    startLine: 38
  assemblies:
  - FastEndpoints
  namespace: FastEndpoints
  summary: endpoint discovery &amp; registration settings
  example: []
  syntax:
    content: public EndpointOptions Endpoints { get; }
    parameters: []
    return:
      type: FastEndpoints.EndpointOptions
    content.vb: Public ReadOnly Property Endpoints As EndpointOptions
  overload: FastEndpoints.Config.Endpoints*
- uid: FastEndpoints.Config.Errors
  commentId: P:FastEndpoints.Config.Errors
  id: Errors
  parent: FastEndpoints.Config
  langs:
  - csharp
  - vb
  name: Errors
  nameWithType: Config.Errors
  fullName: FastEndpoints.Config.Errors
  type: Property
  source:
    id: Errors
    path: D:\SOURCE-CONTROL\FastEndpoints\Src\Library\Config\Config.cs
    startLine: 43
  assemblies:
  - FastEndpoints
  namespace: FastEndpoints
  summary: error response customization settings
  example: []
  syntax:
    content: public ErrorOptions Errors { get; }
    parameters: []
    return:
      type: FastEndpoints.ErrorOptions
    content.vb: Public ReadOnly Property Errors As ErrorOptions
  overload: FastEndpoints.Config.Errors*
- uid: FastEndpoints.Config.Security
  commentId: P:FastEndpoints.Config.Security
  id: Security
  parent: FastEndpoints.Config
  langs:
  - csharp
  - vb
  name: Security
  nameWithType: Config.Security
  fullName: FastEndpoints.Config.Security
  type: Property
  source:
    id: Security
    path: D:\SOURCE-CONTROL\FastEndpoints\Src\Library\Config\Config.cs
    startLine: 48
  assemblies:
  - FastEndpoints
  namespace: FastEndpoints
  summary: security related settings
  example: []
  syntax:
    content: public SecurityOptions Security { get; }
    parameters: []
    return:
      type: FastEndpoints.SecurityOptions
    content.vb: Public ReadOnly Property Security As SecurityOptions
  overload: FastEndpoints.Config.Security*
- uid: FastEndpoints.Config.Serializer
  commentId: P:FastEndpoints.Config.Serializer
  id: Serializer
  parent: FastEndpoints.Config
  langs:
  - csharp
  - vb
  name: Serializer
  nameWithType: Config.Serializer
  fullName: FastEndpoints.Config.Serializer
  type: Property
  source:
    id: Serializer
    path: D:\SOURCE-CONTROL\FastEndpoints\Src\Library\Config\Config.cs
    startLine: 53
  assemblies:
  - FastEndpoints
  namespace: FastEndpoints
  summary: settings for customizing serialization behavior
  example: []
  syntax:
    content: public SerializerOptions Serializer { get; }
    parameters: []
    return:
      type: FastEndpoints.SerializerOptions
    content.vb: Public ReadOnly Property Serializer As SerializerOptions
  overload: FastEndpoints.Config.Serializer*
- uid: FastEndpoints.Config.Throttle
  commentId: P:FastEndpoints.Config.Throttle
  id: Throttle
  parent: FastEndpoints.Config
  langs:
  - csharp
  - vb
  name: Throttle
  nameWithType: Config.Throttle
  fullName: FastEndpoints.Config.Throttle
  type: Property
  source:
    id: Throttle
    path: D:\SOURCE-CONTROL\FastEndpoints\Src\Library\Config\Config.cs
    startLine: 58
  assemblies:
  - FastEndpoints
  namespace: FastEndpoints
  summary: endpoint throttling/ rate limiting settings
  example: []
  syntax:
    content: public ThrottleOptions Throttle { get; }
    parameters: []
    return:
      type: FastEndpoints.ThrottleOptions
    content.vb: Public ReadOnly Property Throttle As ThrottleOptions
  overload: FastEndpoints.Config.Throttle*
- uid: FastEndpoints.Config.Versioning
  commentId: P:FastEndpoints.Config.Versioning
  id: Versioning
  parent: FastEndpoints.Config
  langs:
  - csharp
  - vb
  name: Versioning
  nameWithType: Config.Versioning
  fullName: FastEndpoints.Config.Versioning
  type: Property
  source:
    id: Versioning
    path: D:\SOURCE-CONTROL\FastEndpoints\Src\Library\Config\Config.cs
    startLine: 63
  assemblies:
  - FastEndpoints
  namespace: FastEndpoints
  summary: endpoint versioning settings
  example: []
  syntax:
    content: public VersioningOptions Versioning { get; }
    parameters: []
    return:
      type: FastEndpoints.VersioningOptions
    content.vb: Public ReadOnly Property Versioning As VersioningOptions
  overload: FastEndpoints.Config.Versioning*
- uid: FastEndpoints.Config.Validation
  commentId: P:FastEndpoints.Config.Validation
  id: Validation
  parent: FastEndpoints.Config
  langs:
  - csharp
  - vb
  name: Validation
  nameWithType: Config.Validation
  fullName: FastEndpoints.Config.Validation
  type: Property
  source:
    id: Validation
    path: D:\SOURCE-CONTROL\FastEndpoints\Src\Library\Config\Config.cs
    startLine: 68
  assemblies:
  - FastEndpoints
  namespace: FastEndpoints
  summary: endpoint validation settings
  example: []
  syntax:
    content: public ValidationOptions Validation { get; }
    parameters: []
    return:
      type: FastEndpoints.ValidationOptions
    content.vb: Public ReadOnly Property Validation As ValidationOptions
  overload: FastEndpoints.Config.Validation*
references:
- uid: FastEndpoints
  commentId: N:FastEndpoints
  href: FastEndpoints.html
  name: FastEndpoints
  nameWithType: FastEndpoints
  fullName: FastEndpoints
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: FastEndpoints.Config.Binding*
  commentId: Overload:FastEndpoints.Config.Binding
  href: FastEndpoints.Config.html#FastEndpoints_Config_Binding
  name: Binding
  nameWithType: Config.Binding
  fullName: FastEndpoints.Config.Binding
- uid: FastEndpoints.BindingOptions
  commentId: T:FastEndpoints.BindingOptions
  parent: FastEndpoints
  href: FastEndpoints.BindingOptions.html
  name: BindingOptions
  nameWithType: BindingOptions
  fullName: FastEndpoints.BindingOptions
- uid: FastEndpoints.Config.Endpoints*
  commentId: Overload:FastEndpoints.Config.Endpoints
  href: FastEndpoints.Config.html#FastEndpoints_Config_Endpoints
  name: Endpoints
  nameWithType: Config.Endpoints
  fullName: FastEndpoints.Config.Endpoints
- uid: FastEndpoints.EndpointOptions
  commentId: T:FastEndpoints.EndpointOptions
  parent: FastEndpoints
  href: FastEndpoints.EndpointOptions.html
  name: EndpointOptions
  nameWithType: EndpointOptions
  fullName: FastEndpoints.EndpointOptions
- uid: FastEndpoints.Config.Errors*
  commentId: Overload:FastEndpoints.Config.Errors
  href: FastEndpoints.Config.html#FastEndpoints_Config_Errors
  name: Errors
  nameWithType: Config.Errors
  fullName: FastEndpoints.Config.Errors
- uid: FastEndpoints.ErrorOptions
  commentId: T:FastEndpoints.ErrorOptions
  parent: FastEndpoints
  href: FastEndpoints.ErrorOptions.html
  name: ErrorOptions
  nameWithType: ErrorOptions
  fullName: FastEndpoints.ErrorOptions
- uid: FastEndpoints.Config.Security*
  commentId: Overload:FastEndpoints.Config.Security
  href: FastEndpoints.Config.html#FastEndpoints_Config_Security
  name: Security
  nameWithType: Config.Security
  fullName: FastEndpoints.Config.Security
- uid: FastEndpoints.SecurityOptions
  commentId: T:FastEndpoints.SecurityOptions
  parent: FastEndpoints
  href: FastEndpoints.SecurityOptions.html
  name: SecurityOptions
  nameWithType: SecurityOptions
  fullName: FastEndpoints.SecurityOptions
- uid: FastEndpoints.Config.Serializer*
  commentId: Overload:FastEndpoints.Config.Serializer
  href: FastEndpoints.Config.html#FastEndpoints_Config_Serializer
  name: Serializer
  nameWithType: Config.Serializer
  fullName: FastEndpoints.Config.Serializer
- uid: FastEndpoints.SerializerOptions
  commentId: T:FastEndpoints.SerializerOptions
  parent: FastEndpoints
  href: FastEndpoints.SerializerOptions.html
  name: SerializerOptions
  nameWithType: SerializerOptions
  fullName: FastEndpoints.SerializerOptions
- uid: FastEndpoints.Config.Throttle*
  commentId: Overload:FastEndpoints.Config.Throttle
  href: FastEndpoints.Config.html#FastEndpoints_Config_Throttle
  name: Throttle
  nameWithType: Config.Throttle
  fullName: FastEndpoints.Config.Throttle
- uid: FastEndpoints.ThrottleOptions
  commentId: T:FastEndpoints.ThrottleOptions
  parent: FastEndpoints
  href: FastEndpoints.ThrottleOptions.html
  name: ThrottleOptions
  nameWithType: ThrottleOptions
  fullName: FastEndpoints.ThrottleOptions
- uid: FastEndpoints.Config.Versioning*
  commentId: Overload:FastEndpoints.Config.Versioning
  href: FastEndpoints.Config.html#FastEndpoints_Config_Versioning
  name: Versioning
  nameWithType: Config.Versioning
  fullName: FastEndpoints.Config.Versioning
- uid: FastEndpoints.VersioningOptions
  commentId: T:FastEndpoints.VersioningOptions
  parent: FastEndpoints
  href: FastEndpoints.VersioningOptions.html
  name: VersioningOptions
  nameWithType: VersioningOptions
  fullName: FastEndpoints.VersioningOptions
- uid: FastEndpoints.Config.Validation*
  commentId: Overload:FastEndpoints.Config.Validation
  href: FastEndpoints.Config.html#FastEndpoints_Config_Validation
  name: Validation
  nameWithType: Config.Validation
  fullName: FastEndpoints.Config.Validation
- uid: FastEndpoints.ValidationOptions
  commentId: T:FastEndpoints.ValidationOptions
  parent: FastEndpoints
  href: FastEndpoints.ValidationOptions.html
  name: ValidationOptions
  nameWithType: ValidationOptions
  fullName: FastEndpoints.ValidationOptions
