### YamlMime:ManagedReference
items:
- uid: FastEndpoints.Swagger.TagCase
  commentId: T:FastEndpoints.Swagger.TagCase
  id: TagCase
  parent: FastEndpoints.Swagger
  children:
  - FastEndpoints.Swagger.TagCase.LowerCase
  - FastEndpoints.Swagger.TagCase.None
  - FastEndpoints.Swagger.TagCase.TitleCase
  langs:
  - csharp
  - vb
  name: TagCase
  nameWithType: TagCase
  fullName: FastEndpoints.Swagger.TagCase
  type: Enum
  assemblies:
  - FastEndpoints.Swagger
  namespace: FastEndpoints.Swagger
  summary: enum values for swagger tag naming strategy
  example: []
  syntax:
    content: public enum TagCase
    content.vb: Public Enum TagCase
- uid: FastEndpoints.Swagger.TagCase.None
  commentId: F:FastEndpoints.Swagger.TagCase.None
  id: None
  parent: FastEndpoints.Swagger.TagCase
  langs:
  - csharp
  - vb
  name: None
  nameWithType: TagCase.None
  fullName: FastEndpoints.Swagger.TagCase.None
  type: Field
  assemblies:
  - FastEndpoints.Swagger
  namespace: FastEndpoints.Swagger
  syntax:
    content: None = 0
    return:
      type: FastEndpoints.Swagger.TagCase
- uid: FastEndpoints.Swagger.TagCase.TitleCase
  commentId: F:FastEndpoints.Swagger.TagCase.TitleCase
  id: TitleCase
  parent: FastEndpoints.Swagger.TagCase
  langs:
  - csharp
  - vb
  name: TitleCase
  nameWithType: TagCase.TitleCase
  fullName: FastEndpoints.Swagger.TagCase.TitleCase
  type: Field
  assemblies:
  - FastEndpoints.Swagger
  namespace: FastEndpoints.Swagger
  syntax:
    content: TitleCase = 1
    return:
      type: FastEndpoints.Swagger.TagCase
- uid: FastEndpoints.Swagger.TagCase.LowerCase
  commentId: F:FastEndpoints.Swagger.TagCase.LowerCase
  id: LowerCase
  parent: FastEndpoints.Swagger.TagCase
  langs:
  - csharp
  - vb
  name: LowerCase
  nameWithType: TagCase.LowerCase
  fullName: FastEndpoints.Swagger.TagCase.LowerCase
  type: Field
  assemblies:
  - FastEndpoints.Swagger
  namespace: FastEndpoints.Swagger
  syntax:
    content: LowerCase = 2
    return:
      type: FastEndpoints.Swagger.TagCase
references:
- uid: FastEndpoints.Swagger
  commentId: N:FastEndpoints.Swagger
  href: FastEndpoints.html
  name: FastEndpoints.Swagger
  nameWithType: FastEndpoints.Swagger
  fullName: FastEndpoints.Swagger
  spec.csharp:
  - uid: FastEndpoints
    name: FastEndpoints
    href: FastEndpoints.html
  - name: .
  - uid: FastEndpoints.Swagger
    name: Swagger
    href: FastEndpoints.Swagger.html
  spec.vb:
  - uid: FastEndpoints
    name: FastEndpoints
    href: FastEndpoints.html
  - name: .
  - uid: FastEndpoints.Swagger
    name: Swagger
    href: FastEndpoints.Swagger.html
- uid: FastEndpoints.Swagger.TagCase
  commentId: T:FastEndpoints.Swagger.TagCase
  parent: FastEndpoints.Swagger
  href: FastEndpoints.Swagger.TagCase.html
  name: TagCase
  nameWithType: TagCase
  fullName: FastEndpoints.Swagger.TagCase
