### YamlMime:ManagedReference
items:
- uid: FastEndpoints.Swagger.TagCase
  commentId: T:FastEndpoints.Swagger.TagCase
  id: TagCase
  parent: FastEndpoints.Swagger
  children:
  - FastEndpoints.Swagger.TagCase.LowerCase
  - FastEndpoints.Swagger.TagCase.None
  - FastEndpoints.Swagger.TagCase.TitleCase
  langs:
  - csharp
  - vb
  name: TagCase
  nameWithType: TagCase
  fullName: FastEndpoints.Swagger.TagCase
  type: Enum
  source:
    id: TagCase
    path: D:\SOURCE-CONTROL\FastEndpoints\Library\Src\Swagger\TagCase.cs
    startLine: 5
  assemblies:
  - FastEndpoints.Swagger
  namespace: FastEndpoints.Swagger
  summary: "\nenum values for swagger tag naming strategy\n"
  example: []
  syntax:
    content: public enum TagCase
    content.vb: Public Enum TagCase
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: FastEndpoints.Swagger.TagCase.None
  commentId: F:FastEndpoints.Swagger.TagCase.None
  id: None
  parent: FastEndpoints.Swagger.TagCase
  langs:
  - csharp
  - vb
  name: None
  nameWithType: TagCase.None
  fullName: FastEndpoints.Swagger.TagCase.None
  type: Field
  source:
    id: None
    path: D:\SOURCE-CONTROL\FastEndpoints\Library\Src\Swagger\TagCase.cs
    startLine: 7
  assemblies:
  - FastEndpoints.Swagger
  namespace: FastEndpoints.Swagger
  syntax:
    content: None = 0
    return:
      type: FastEndpoints.Swagger.TagCase
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: FastEndpoints.Swagger.TagCase.TitleCase
  commentId: F:FastEndpoints.Swagger.TagCase.TitleCase
  id: TitleCase
  parent: FastEndpoints.Swagger.TagCase
  langs:
  - csharp
  - vb
  name: TitleCase
  nameWithType: TagCase.TitleCase
  fullName: FastEndpoints.Swagger.TagCase.TitleCase
  type: Field
  source:
    id: TitleCase
    path: D:\SOURCE-CONTROL\FastEndpoints\Library\Src\Swagger\TagCase.cs
    startLine: 8
  assemblies:
  - FastEndpoints.Swagger
  namespace: FastEndpoints.Swagger
  syntax:
    content: TitleCase = 1
    return:
      type: FastEndpoints.Swagger.TagCase
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: FastEndpoints.Swagger.TagCase.LowerCase
  commentId: F:FastEndpoints.Swagger.TagCase.LowerCase
  id: LowerCase
  parent: FastEndpoints.Swagger.TagCase
  langs:
  - csharp
  - vb
  name: LowerCase
  nameWithType: TagCase.LowerCase
  fullName: FastEndpoints.Swagger.TagCase.LowerCase
  type: Field
  source:
    id: LowerCase
    path: D:\SOURCE-CONTROL\FastEndpoints\Library\Src\Swagger\TagCase.cs
    startLine: 9
  assemblies:
  - FastEndpoints.Swagger
  namespace: FastEndpoints.Swagger
  syntax:
    content: LowerCase = 2
    return:
      type: FastEndpoints.Swagger.TagCase
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: FastEndpoints.Swagger
  commentId: N:FastEndpoints.Swagger
  name: FastEndpoints.Swagger
  nameWithType: FastEndpoints.Swagger
  fullName: FastEndpoints.Swagger
- uid: FastEndpoints.Swagger.TagCase
  commentId: T:FastEndpoints.Swagger.TagCase
  parent: FastEndpoints.Swagger
  name: TagCase
  nameWithType: TagCase
  fullName: FastEndpoints.Swagger.TagCase
