### YamlMime:ManagedReference
items:
- uid: FastEndpoints.Swagger
  commentId: N:FastEndpoints.Swagger
  id: FastEndpoints.Swagger
  children:
  - FastEndpoints.Swagger.Extensions
  - FastEndpoints.Swagger.GlobalConfig
  - FastEndpoints.Swagger.TagCase
  langs:
  - csharp
  - vb
  name: FastEndpoints.Swagger
  nameWithType: FastEndpoints.Swagger
  fullName: FastEndpoints.Swagger
  type: Namespace
  assemblies:
  - FastEndpoints.Swagger
references:
- uid: FastEndpoints.Swagger.Extensions
  commentId: T:FastEndpoints.Swagger.Extensions
  name: Extensions
  nameWithType: Extensions
  fullName: FastEndpoints.Swagger.Extensions
- uid: FastEndpoints.Swagger.GlobalConfig
  commentId: T:FastEndpoints.Swagger.GlobalConfig
  name: GlobalConfig
  nameWithType: GlobalConfig
  fullName: FastEndpoints.Swagger.GlobalConfig
- uid: FastEndpoints.Swagger.TagCase
  commentId: T:FastEndpoints.Swagger.TagCase
  parent: FastEndpoints.Swagger
  name: TagCase
  nameWithType: TagCase
  fullName: FastEndpoints.Swagger.TagCase
- uid: FastEndpoints.Swagger
  commentId: N:FastEndpoints.Swagger
  name: FastEndpoints.Swagger
  nameWithType: FastEndpoints.Swagger
  fullName: FastEndpoints.Swagger
